version: "3.7"
services:
  collector:
    build:
      context: .
      dockerfile: ./e2e/docker/Dockerfile.tool
    ports:
      - 19876:19876
      - 12800:12800

  consumer:
    build:
      context: .
      dockerfile: ./e2e/docker/Dockerfile
    expose: 
      - 8082
    command: cargo run -- --mode consumer
    depends_on:
      - collector

  producer:
    build:
      context: .
      dockerfile: ./e2e/docker/Dockerfile
    ports:
      - 8081:8081
    command: cargo run -- --mode producer
    depends_on:
      - collector
      - consumer