# This is a basic workflow to help you get started with Actions

name: cpp2sky test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install Rust
        run: |
          rustup toolchain install stable --component clippy --component rustfmt
      - name: Format
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy
